### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by FCare**
Part of the pull request with H/V cleanup

### CODE REVIEW

**Comment by devmiyax** [comment]
pthread_cancel is not implemented in Android. Do you have any other ideas?

```
src/libyabause.a(thr-linux.c.o):thr-linux.c:function YabThreadCancel: error: undefined reference to 'pthread_cancel'
```

**Comment by FCare** [comment]
I will take a look

**Comment by devmiyax** [comment]
I ran this pull request using QT version on Windows.
It locks same code line. can you check?

```
>	yabause.exe!YabThreadCondWait(void * * ctx, void * * mtx) Line 311	C
 	yabause.exe!syncWithSH2(...) Line 5243	C
 	yabause.exe!ScspAsynMain(void * p) Line 5311	C
 	yabause.exe!wrapper(void * hnd) Line 52	C
```

**Comment by FCare** [comment]
Yes, i fixed it on the branch align-dynarec but i did not backport yet. You
can take all patches on this branch. It has biebeen n tested by siskoo.

**Pull request closed without merging**
