### PR TITLE
Cleanup of V/H sync

### PR DESCRIPTION
**Pull request by FCare**
Devmiyax, 
I have a set of patches that clean up the V/H sync management.
It is using now a state machine which is easier to debug. I also increased the cycle accuracy. I noticed that with old code, number of cycles spent on one line was about 30 cycles more than expected, which gives about 9000 cycles more per frame (so around 4 lines more per screen). B.Siskoo did a lot of test and it seems it does not introduce any regressions. But it is fixing some games that were not booting like Chaos Control or Alone in the Dark.

I also fixed the cpu load of the scsp AsynMain thread. A usleep of 0 has no effect, meaning that the thread is always looping. I fixed the sleep duration and cpu load is drastically reduced. Thanks linux perf tool :-)

I hope you can merge those patches, that way, we will be able to close some bugs :-)
Francois

### CODE REVIEW

**Comment by devmiyax** [comment]
Wow! huge changes! Can you check there is no regression on  house of the dead and street fighter zero 3 and Draculax and sonic jam?

**Comment by devmiyax** [comment]
and burning rangers

**Comment by FCare** [comment]
Let's check :-)

**Comment by FCare** [comment]
at least, the last patch about scsp might be really interesting. For low cpu devices, it might increase the framerate.

**Comment by FCare** [comment]
House of the dead is not working on my side on a stock 0.4.6. It does not want to boot. It seems to be the same with the code, so I can not say if it breaks it or not.
Burning Rangers is working fine.
Street Fighter Zero 3 is also working fine.
Dracula X seems also ok. 
I have a white screen with Sonic Jam. It is booting, music is played but screen is white when I press Game. If I press Sonic World, it looks ok. I have the same behavior with 0.4.6.

And all are consuming less than one core of cpu...

But all of this is tested on my ubuntu port. Can you give it a try on your android port, maybe in a test branch?

**Comment by FCare** [comment]
With the US Rom of House of the dead, it seems also quite ok. But I think you might better now what shall be a ok status :-) So I think it is better to double check with your own roms on your side.

**Comment by devmiyax** [comment]
Can you check this?
https://www.youtube.com/watch?v=yWbH1AWUPTI&t=39s

**Comment by FCare** [comment]
GunGriffon is ok.
Dracula X has no clearance.
NBA Jam Tournament (if it this one) seems also ok.

I asked benjamin to test on his side too.

**Comment by BenjaminSiskoo** [comment]
Confirmed, sound good :)

**Comment by BenjaminSiskoo** [comment]
CPU usage (Windows)

yabausecpu

**Comment by devmiyax** [comment]
Ok. I'll check in this weekend on Android devices

**Comment by devmiyax** [comment]
Hi, I've tested some games on SHIELD TV.
On interpreter mode, it works fine. It's amazing! But on Dynarec CPU mode, I found some regressions.
For Android users, Dynarec CPU mode is very important. Can you check?

* Gungriffon: No characters are drawn.
* Gungriffon: Bad Background color.
* Nights: Bad Background color.
* Nights: Textures are broken
* Burning Rangers:  game does not start.
* Daytona USA: does not boot with green screen.
* Daytona USA CE: broken polygons and crash.

gungriffon bad color
gungriffon nocharacterisdrawn
nights bad_color
nights broken textures
daytona_usa_does_not_boot

**Comment by FCare** [comment]
I can check, and it is better with ome games to look at. Thanks :-)
I only have a x86 PC and dynarec on x86_64 is broken so I can not test and debug the dynarec on my ubuntu. But I still have my odroid xu4 board. I have been able to boot an ubuntu mate on it. But the port I am using (sdl) still have some dependencies with SDL2, and SDL2 on odroid xu4 is breaking the openGL driver... I am working to remove SDL dependencies and to make soft renderer working on my sdl port, that way I will be able to debug the dynarec. I will inform you as soon as it is booting on my odroid board.
I also have a shield tv but it is not so easy to develop on since my daughters are using it...

Which dynarec did you test? yours or the one one the main branch?

**Comment by FCare** [comment]
Dynarec seems to be quite unrelated to the patchs. I only moved ome initialisation in an other subroutines and I think t global variables are not initialized anymore. I blindly push this patch, I think it should at least partially fix the dynarec. Can you give it a try?

**Comment by devmiyax** [comment]
OMG! I missed compiling options(YAB_WANT_ARM7). it works fine now.

**Comment by FCare** [comment]
I fixed dynarec on all cpus. There was a call missing and a call with a bad argument...

**Comment by FCare** [comment]
I did some performance test on my x86_64 pc, using the perf tool. Dynarec usage only save some percent of cpu compared to standard interpreter.

Using standard interpreter:
SH2_interpreter takes only 3% of the full load but Vdp2DrawRotation takes more than 15% and Vdp1ReadTexture takes a bit less than 7%

Using sh2 dynarec:
Vdp2DrawRotation takes more than 15% and Vdp1ReadTexture takes a bit less than 7% and the dynarec call are splitted other multiple calls so it is diffcult to evaluate. But at best, we save 3% of cpu.

I am not sure that spending so much time on a ne dynarec is so important, but maybe it is different on ARM devices. At least, I think it is not usefull to port the new dynarec to x86.

**Comment by FCare** [comment]
I am continuing a phase of optimtization. I dropped a cache mechanism I did a while ago. Instead of decding the texture data at each frame, it is storing the texture content into a cache. It is based on the fact that many developers does not change their sprites at each frame. I have tested on many games, it does not seems to introduce glitches. It is reducing the load of Vdp1ReadTexture to around 1% on my PC.

**Comment by devmiyax** [comment]
Hi, these are many purposes( vsync, game pad, vdp1 cache .. etc)  in this pull request as a single pull request 😄 
Can you separate them?

**Comment by FCare** [comment]
I will look at how to split this.

It was not the original plan to have a such big pull request, it is automatically done by github...

**Comment by FCare** [comment]
I had to create one branch per pull request.
In order to have a clean integration, first merge H/V cleanup, then the two others.

**Comment by BenjaminSiskoo** [comment]
yabause

**Pull request closed without merging**
