### PR TITLE
French translations and fixes

### PR DESCRIPTION
**Pull request by deomkds**
Added a French translation by BenjaminSiskoo (Issue #126 ) and tweaked the Brazilian Portuguese translation.

### CODE REVIEW

**Comment by BenjaminSiskoo** [comment]
Thanks to your help :)

**Comment by deomkds** [comment]
No problem. =D

**Comment by devmiyax** [comment]
Merci!

**Comment by BenjaminSiskoo** [comment]
Mu pleasure...

**Pull request merged**
